# Generated by Django 5.2.4 on 2025-07-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('reg_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='students/birth_certificates/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('report_card', models.FileField(blank=True, null=True, upload_to='students/report_cards/')),
            ],
        ),
    ]
