# Generated by Django 5.2.4 on 2025-07-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('week', models.PositiveIntegerField()),
                ('objectives', models.TextField()),
                ('coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_plans', to='staff.staff')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_plans/materials/')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('other', 'Other')], default='pdf', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lesson_plans.lessonplan')),
            ],
        ),
    ]
