name: Deploy static frontend to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Optional: Setup Python for backend checks or tests
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          fi

      # Optional: Run backend tests (customize if needed)
      # - name: Run Backend Tests
      #   run: |
      #     cd backend
      #     pytest

      # Deploy static frontend to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEUCES_2190 }}
          channelId: live
          projectId: deuces-2190
